language: python
python: 2.7
env:
 - TOX_ENV=py34
 - TOX_ENV=py33
 - TOX_ENV=py27
 - TOX_ENV=py26
install:
 - pip install tox
script:
 - tox -e $TOX_ENV -- --cov-report html --cov=awslogs --no-cov-on-fail
after_success:
  coveralls
